const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  createClientFolder: (basePath, clientName) => ipcRenderer.invoke('create-client-folder', basePath, clientName),
  getClientFolderPath: (basePath, clientName) => ipcRenderer.invoke('get-client-folder-path', basePath, clientName),
  getDefaultClientFolder: () => ipcRenderer.invoke('get-default-client-folder'),
  listNoteFiles: (folderPath) => ipcRenderer.invoke('list-note-files', folderPath),
  listFolderContents: (folderPath) => ipcRenderer.invoke('list-folder-contents', folderPath),
  createSubfolder: (parentPath, folderName) => ipcRenderer.invoke('create-subfolder', parentPath, folderName),
  deletePath: (fullPath) => ipcRenderer.invoke('delete-path', fullPath),
  readNote: (folderPath, filename) => ipcRenderer.invoke('read-note', folderPath, filename),
  writeNote: (folderPath, filename, content) => ipcRenderer.invoke('write-note', folderPath, filename, content),
  openFolder: (folderPath) => ipcRenderer.invoke('open-folder', folderPath),
  printHtmlToPdf: (fullHtml) => ipcRenderer.invoke('print-html-to-pdf', fullHtml),
  // Tâches / Projets (Studio Velysion Project Manager)
  getProjects: () => ipcRenderer.invoke('get-projects'),
  getProject: (id) => ipcRenderer.invoke('get-project', id),
  createProject: (project) => ipcRenderer.invoke('create-project', project),
  updateProject: (id, project) => ipcRenderer.invoke('update-project', id, project),
  deleteProject: (id) => ipcRenderer.invoke('delete-project', id),
  archiveProject: (id) => ipcRenderer.invoke('archive-project', id),
  unarchiveProject: (id) => ipcRenderer.invoke('unarchive-project', id),
  duplicateProject: (id) => ipcRenderer.invoke('duplicate-project', id),
  getTasks: (projectId) => ipcRenderer.invoke('get-tasks', projectId),
  getTask: (id) => ipcRenderer.invoke('get-task', id),
  createTask: (task) => ipcRenderer.invoke('create-task', task),
  updateTask: (id, task) => ipcRenderer.invoke('update-task', id, task),
  deleteTask: (id) => ipcRenderer.invoke('delete-task', id),
  updateTaskStatus: (id, status) => ipcRenderer.invoke('update-task-status', id, status),
  getTaskStats: (projectId) => ipcRenderer.invoke('get-task-stats', projectId),
  getNotes: (projectId) => ipcRenderer.invoke('get-notes', projectId),
  updateNotes: (projectId, content) => ipcRenderer.invoke('update-notes', projectId, content),
  getProjectUpdates: (projectId) => ipcRenderer.invoke('get-project-updates', projectId),
  createProjectUpdate: (update) => ipcRenderer.invoke('create-project-update', update),
  updateProjectUpdate: (id, update) => ipcRenderer.invoke('update-project-update', id, update),
  deleteProjectUpdate: (id) => ipcRenderer.invoke('delete-project-update', id),
  getActivityLog: (limit) => ipcRenderer.invoke('get-activity-log', limit),
  logActivity: (activity) => ipcRenderer.invoke('log-activity', activity),
  // Google Drive (sauvegardes cloud)
  googleDriveConnect: (clientId, clientSecret) => ipcRenderer.invoke('google-drive-connect', clientId, clientSecret),
  googleDriveSave: (jsonContent) => ipcRenderer.invoke('google-drive-save', jsonContent),
  googleDriveRestore: () => ipcRenderer.invoke('google-drive-restore'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
});
